before:
  hooks:
    - go mod tidy
builds:
  - id: tlagent
    main: cmd/agent/main.go
    binary: tlagent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
      - amd64
    goarm:
      - "6"
  - id: tlserver
    main: cmd/server/main.go
    binary: tlserver
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
      - amd64
archives:
  - replacements:
      amd64: x86_64
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request'
