before:
  hooks:
    - go mod tidy
builds:
  - main: cmd/agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
      - amd64
    goarm:
      - "7"
archives:
  - replacements:
      amd64: x86_64
