before:
  hooks:
    - go mod tidy
builds:
  - main: cmd/agent
    binary: tlagent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
      - amd64
    goarm:
      - "6"
  - main: cmd/server
    binary: tlserver
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      amd64: x86_64
