name: CI

on:
  pull_request:
  push:
    branches:
    - "main"

jobs:
  lint:
    name: Go lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2.5
        with:
          version: latest

  test:
    name: Go test & coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # See https://community.codecov.com/t/issue-detecting-commit-sha-please-run-actions-checkout-with-fetch-depth-1-or-set-to-0/2571
      - uses: actions/setup-go@v2.1
        with:
          go-version: 1.17.x
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
