name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint:
    name: Go lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.44

  test:
    name: Go test & coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # See https://community.codecov.com/t/issue-detecting-commit-sha-please-run-actions-checkout-with-fetch-depth-1-or-set-to-0/2571
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
